# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-02 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180426_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='teater',
            name='image',
            field=models.ImageField(default='', max_length=200, upload_to='teacher/%Y/%m', verbose_name='\u6559\u5e08\u5934\u50cf'),
        ),
    ]
