# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-03 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180403_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('md5sum', models.CharField(max_length=7)),
                ('gate_ip', models.CharField(max_length=32)),
                ('gate_port', models.IntegerField(default=9310)),
                ('platform', models.CharField(max_length=32)),
                ('in_use', models.IntegerField(default=1)),
                ('dns_push_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('modify_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': 'Gate\u4fe1\u606f\u8868',
                'verbose_name_plural': 'Gate\u4fe1\u606f\u8868',
            },
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u9001\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '\u6ce8\u518c'), ('forget', '\u627e\u56de\u5bc6\u7801')], max_length=10, verbose_name='\u9a8c\u8bc1\u7801\u7c7b\u578b'),
        ),
    ]
