# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-12 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180403_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': '\u6e20\u9053\u4fe1\u606f\u8868', 'verbose_name_plural': '\u6e20\u9053\u4fe1\u606f\u8868'},
        ),
    ]
